#!/usr/bin/env python3
"""
Track 18: Reverse ETL Confluent Kafka Connect & Google Pub/Sub
Simulates a Google Pub/Sub consumer handling a network retry storm.
Demonstrates using a Redis cache with atomic SETNX (Set if Not Exists)
to build an idempotent deduplication layer, effectively bridging the 
'Exactly-Once Impedance Mismatch'.
"""

import time
import uuid
import random
import threading
import json
import logging
from typing import List, Dict

# Attempt to import redis. If not installed, we provide a graceful fallback
# to a mock Redis class to ensure the simulation can always run.
try:
    import redis
    REDIS_AVAILABLE = True
except ImportError:
    REDIS_AVAILABLE = False
    logging.warning("The 'redis' Python package is not installed. Using MockRedis for simulation.")

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - [%(levelname)s] - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)

class MockRedis:
    """
    A minimal mock of the Redis client for simulation purposes if the real
    Redis server or Python package is unavailable. It simulates the atomic
    behavior of SETNX (set(nx=True)).
    """
    def __init__(self):
        self._cache: Dict[str, str] = {}
        self._lock = threading.Lock()
        
    def set(self, name: str, value: str, ex: int = None, nx: bool = False):
        with self._lock:
            if nx and name in self._cache:
                return None # Simulate SETNX failure (key exists)
            
            self._cache[name] = value
            return True # Simulate SETNX success (key did not exist)
            
    def flushdb(self):
        with self._lock:
            self._cache.clear()

class ReverseETLPipeline:
    """
    Simulates the Reverse ETL pipeline where Kafka Connect pushes predictive
    analytics events to Google Cloud Pub/Sub, which are then consumed by a CRM
    ingestion worker.
    """
    def __init__(self, use_real_redis: bool = False, redis_host: str = 'localhost', redis_port: int = 6379):
        # Configure Redis connection
        if use_real_redis and REDIS_AVAILABLE:
            try:
                self.redis_client = redis.Redis(host=redis_host, port=redis_port, decode_responses=True)
                self.redis_client.ping()
                logging.info(f"Connected to real Redis instance at {redis_host}:{redis_port}")
            except redis.ConnectionError:
                logging.error(f"Failed to connect to Redis at {redis_host}:{redis_port}. Falling back to MockRedis.")
                self.redis_client = MockRedis()
        else:
            logging.info("Initializing MockRedis for atomic SETNX deduplication.")
            self.redis_client = MockRedis()
            
        # Clean state for simulation
        self.redis_client.flushdb()
        
        # Metrics tracking
        self.total_messages_received = 0
        self.duplicate_messages_dropped = 0
        self.unique_messages_processed = 0

    def simulate_pubsub_retry_storm(self, num_unique_events: int = 100, duplicate_probability: float = 0.4) -> List[Dict]:
        """
        Generates a stream of simulated Pub/Sub messages. Due to network partitions,
        ACKs are dropped, causing Pub/Sub's at-least-once delivery mechanism to 
        resend duplicates.
        """
        logging.info(f"Generating {num_unique_events} unique CRM ingestion events...")
        stream = []
        
        for i in range(num_unique_events):
            # The message ID is generated by the source system (e.g., Kafka)
            # and passed through Pub/Sub as an attribute.
            msg_id = f"evt_{uuid.uuid4().hex[:12]}"
            
            payload = {
                "message_id": msg_id,
                "customer_id": f"CUST_{random.randint(1000, 9999)}",
                "churn_probability": round(random.uniform(0.7, 0.99), 2),
                "recommended_action": "ISSUE_RETENTION_DISCOUNT",
                "timestamp": int(time.time() * 1000)
            }
            
            # Append the original message
            stream.append(payload)
            
            # Simulate network failure / dropped ACK resulting in a duplicate delivery
            if random.random() < duplicate_probability:
                stream.append(payload.copy())
                # Sometimes network storms result in multiple duplicates!
                if random.random() < (duplicate_probability / 2):
                    stream.append(payload.copy())
                    
        # Shuffle the stream to simulate out-of-order delivery
        random.shuffle(stream)
        logging.info(f"Generated stream of {len(stream)} total messages ({len(stream) - num_unique_events} duplicates).")
        return stream

    def process_message_idempotently(self, message: Dict):
        """
        The core ingestion logic. Utilizes Redis SETNX to achieve idempotency.
        """
        self.total_messages_received += 1
        msg_id = message["message_id"]
        
        # ---------------------------------------------------------------------
        # THE IDEMPOTENT BOUNDARY
        # ---------------------------------------------------------------------
        # We attempt to set the message ID in Redis.
        # nx=True translates to the atomic SETNX operation.
        # ex=86400 sets an expiration (TTL) of 24 hours to prevent memory bloat.
        #
        # If the key did NOT exist, Redis sets it and returns True.
        # If the key ALREADY existed, Redis does nothing and returns None/False.
        # Because Redis is single-threaded, this check-and-set is strictly atomic.
        
        is_new_message = self.redis_client.set(
            name=f"processed_msg:{msg_id}",
            value="1",
            ex=86400, 
            nx=True
        )
        
        if not is_new_message:
            # The atomic SETNX failed. We have already seen this message ID!
            self.duplicate_messages_dropped += 1
            logging.debug(f"Duplicate detected and DROPPED: {msg_id}")
            return
            
        # ---------------------------------------------------------------------
        # BUSINESS LOGIC
        # ---------------------------------------------------------------------
        # We only reach here if the message is guaranteed unique.
        self.unique_messages_processed += 1
        customer = message["customer_id"]
        action = message["recommended_action"]
        logging.debug(f"Processing UNIQUE event: {msg_id} -> Executing {action} for {customer}")
        
        # Simulate CRM API latency
        time.sleep(0.01)

def run_simulation():
    print("=" * 80)
    print("REVERSE ETL IMPEDANCE MISMATCH: IDEMPOTENT CONSUMER SIMULATION")
    print("=" * 80)
    
    # Initialize pipeline
    pipeline = ReverseETLPipeline(use_real_redis=True)
    
    # Generate chaotic stream
    UNIQUE_EVENTS = 500
    message_stream = pipeline.simulate_pubsub_retry_storm(
        num_unique_events=UNIQUE_EVENTS, 
        duplicate_probability=0.6 # High probability of network retry storm
    )
    
    print("\n[STARTING INGESTION]")
    print(f"Streaming {len(message_stream)} raw events from Pub/Sub into CRM Worker...")
    
    start_time = time.time()
    
    # Process messages (simulating a single worker thread)
    for index, msg in enumerate(message_stream):
        pipeline.process_message_idempotently(msg)
        if (index + 1) % 100 == 0:
            logging.info(f"Processed {index + 1}/{len(message_stream)} messages from queue...")
            
    end_time = time.time()
    
    print("\n" + "=" * 80)
    print("                      PIPELINE EXECUTION AUDIT")
    print("=" * 80)
    print(f"Total Raw Messages Received from Pub/Sub:  {pipeline.total_messages_received}")
    print(f"Duplicate Messages Blocked by Redis SETNX: {pipeline.duplicate_messages_dropped}")
    print(f"Unique Events Committed to CRM:            {pipeline.unique_messages_processed}")
    print("-" * 80)
    
    if pipeline.unique_messages_processed == UNIQUE_EVENTS:
        print("[SUCCESS] Exactly-Once Semantics achieved across the Pub/Sub boundary.")
    else:
        print(f"[FAILED] Expected {UNIQUE_EVENTS} commits, got {pipeline.unique_messages_processed}.")
        
    print(f"Total execution time: {(end_time - start_time):.2f} seconds")
    print("=" * 80)

if __name__ == "__main__":
    run_simulation()
