# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_state_pb2 as agent__state__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_state_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentStateServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransferState = channel.stream_unary(
                '/adk_mesh.AgentStateService/TransferState',
                request_serializer=agent__state__pb2.AgentStatePayload.SerializeToString,
                response_deserializer=agent__state__pb2.TransferStatus.FromString,
                _registered_method=True)
        self.GetCheckpoint = channel.unary_unary(
                '/adk_mesh.AgentStateService/GetCheckpoint',
                request_serializer=agent__state__pb2.CheckpointRequest.SerializeToString,
                response_deserializer=agent__state__pb2.CheckpointResponse.FromString,
                _registered_method=True)


class AgentStateServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def TransferState(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentStateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransferState': grpc.stream_unary_rpc_method_handler(
                    servicer.TransferState,
                    request_deserializer=agent__state__pb2.AgentStatePayload.FromString,
                    response_serializer=agent__state__pb2.TransferStatus.SerializeToString,
            ),
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=agent__state__pb2.CheckpointRequest.FromString,
                    response_serializer=agent__state__pb2.CheckpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adk_mesh.AgentStateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adk_mesh.AgentStateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentStateService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransferState(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/adk_mesh.AgentStateService/TransferState',
            agent__state__pb2.AgentStatePayload.SerializeToString,
            agent__state__pb2.TransferStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adk_mesh.AgentStateService/GetCheckpoint',
            agent__state__pb2.CheckpointRequest.SerializeToString,
            agent__state__pb2.CheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
