# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_state.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'agent_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61gent_state.proto\x12\x08\x61\x64k_mesh\"T\n\nTokenUsage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x05\")\n\x0bMemoryEntry\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"t\n\x0eTensorMetadata\x12\x0e\n\x06layers\x18\x01 \x01(\x05\x12\r\n\x05heads\x18\x02 \x01(\x05\x12\x10\n\x08head_dim\x18\x03 \x01(\x05\x12\x18\n\x10kv_cache_address\x18\x04 \x01(\t\x12\x17\n\x0f\x62ytes_allocated\x18\x05 \x01(\x03\"\xab\x02\n\x11\x41gentStatePayload\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nagent_role\x18\x02 \x01(\t\x12\x12\n\nturn_index\x18\x03 \x01(\x05\x12)\n\x0btoken_usage\x18\x04 \x01(\x0b\x32\x14.adk_mesh.TokenUsage\x12\x1a\n\x12\x61\x63tive_constraints\x18\x05 \x03(\t\x12\x34\n\x15\x63onversational_memory\x18\x06 \x03(\x0b\x32\x15.adk_mesh.MemoryEntry\x12\x31\n\x0ftensor_metadata\x18\x07 \x01(\x0b\x32\x18.adk_mesh.TensorMetadata\x12\x13\n\x0b\x63hunk_index\x18\x08 \x01(\x05\x12\x15\n\ris_last_chunk\x18\t \x01(\x08\"W\n\x0eTransferStatus\x12\x16\n\x0estatus_message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1c\n\x14last_processed_chunk\x18\x03 \x01(\x05\"\'\n\x11\x43heckpointRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"J\n\x12\x43heckpointResponse\x12\x1c\n\x14last_processed_chunk\x18\x01 \x01(\x05\x12\x16\n\x0esession_exists\x18\x02 \x01(\x08\x32\xa9\x01\n\x11\x41gentStateService\x12H\n\rTransferState\x12\x1b.adk_mesh.AgentStatePayload\x1a\x18.adk_mesh.TransferStatus(\x01\x12J\n\rGetCheckpoint\x12\x1b.adk_mesh.CheckpointRequest\x1a\x1c.adk_mesh.CheckpointResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENUSAGE']._serialized_start=31
  _globals['_TOKENUSAGE']._serialized_end=115
  _globals['_MEMORYENTRY']._serialized_start=117
  _globals['_MEMORYENTRY']._serialized_end=158
  _globals['_TENSORMETADATA']._serialized_start=160
  _globals['_TENSORMETADATA']._serialized_end=276
  _globals['_AGENTSTATEPAYLOAD']._serialized_start=279
  _globals['_AGENTSTATEPAYLOAD']._serialized_end=578
  _globals['_TRANSFERSTATUS']._serialized_start=580
  _globals['_TRANSFERSTATUS']._serialized_end=667
  _globals['_CHECKPOINTREQUEST']._serialized_start=669
  _globals['_CHECKPOINTREQUEST']._serialized_end=708
  _globals['_CHECKPOINTRESPONSE']._serialized_start=710
  _globals['_CHECKPOINTRESPONSE']._serialized_end=784
  _globals['_AGENTSTATESERVICE']._serialized_start=787
  _globals['_AGENTSTATESERVICE']._serialized_end=956
# @@protoc_insertion_point(module_scope)
